#!/bin/bash
res1() {
wget -O sc.zip "${REPO}sc"
unzip sc.zip
chmod +x menu/*
mv menu/* /usr/local/sbin

wget -O alt.zip "${REPO}alt"
unzip alt.zip
chmod +x all-t/*
mv all-t/* /usr/bin

rm -fr /usr/sbin/xdxl
mkdir -p /usr/sbin/xdxl
mkdir -p /usr/sbin/xdxl/style
wget -O style.zip "${REPO}style.zip"
unzip style.zip
chmod +x style/*
mv style/* /usr/sbin/xdxl/style
}

exe() {
rm -fr menu
rm -fr menu.zip
rm -fr up-x
rm -fr update.sh
rm -fr all-t
rm -fr alt.zip
rm -fr style
rm -fr style.zip
}

res1
exe
