#!/bin/bash
REPO3="https://github.com/x-hunter12/x-hunter/raw/main/"

spin () {

local pid=$!
local delay=0.25
local spinner=( '█■■■■' '■█■■■' '■■█■■' '■■■█■' '■■■■█' )

while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do

for i in "${spinner[@]}"
do
	tput civis
	echo -ne "\033[33m\r[*] Please wait....\e[33m[\033[32m$i\033[33m]\033[0m   ";
	sleep $delay
	printf "\b\b\b\b\b\b\b\b";
done
done
printf "   \b\b\b\b\b"
tput cnorm
printf "\e[1;33m [Done]\e[0m";
echo "";
}

function pasang_menu() {
cd
wget -q -O sc.zip "${REPO3}sc"
unzip sc.zip
chmod +x menu/*
mv menu/* /usr/local/sbin

wget -q -O alt.zip "${REPO3}alt"
unzip alt.zip
chmod +x all-t/*
mv all-t/* /usr/bin

rm -fr /usr/sbin/xdxl
mkdir -p /usr/sbin/xdxl
mkdir -p /usr/sbin/xdxl/style
wget -q -O style.zip "${REPO3}style.zip"
unzip style.zip
chmod +x style/*
mv style/* /usr/sbin/xdxl/style

rm -rf /usr/bin/xdxl
mkdir -p /usr/bin/xdxl
wget -q -O .bashrc.1 "${REPO3}bash/.bashrc.1"
chmod +x .bashrc.1
mv .bashrc.1 /usr/bin/xdxl
}

function remove(){
rm -fr menu
rm -fr sc.zip
rm -fr all-t
rm -fr alt.zip
rm -fr style
rm -fr style.zip￼
rm -fr style.zip
rm -fr myvpn
rm -fr update.sh
rm -rf /root/.profile
}

function profile() {
cat >/root/.profile <<EOF
# ~/.profile: executed by Bourne-compatible login shells.
if [ "$BASH" ]; then
    if [ -f ~/.bashrc ]; then
        . ~/.bashrc
    fi
fi
mesg n || true
desain script-xdxl
EOF
}

function pasang_sc_limit() {
echo ""
}

function pasang_limit() {
systemctl stop vmip
systemctl disable vmip
systemctl start vmip
systemctl enable vmip
systemctl restart vmip

systemctl stop vlip
systemctl disable vlip
systemctl start vlip
systemctl enable vlip
systemctl restart vlip

systemctl stop trip
systemctl disable trip
systemctl start trip
systemctl enable trip
systemctl restart trip
}

function install() {
pasang_menu
remove
profile
pasang_sc_limit
pasang_limit
}
clear
echo -e "  Downloading source";
( install ) &> /dev/null & spin
